### ISSUE TITLE
Why name the theme deppin instead of deepin?

### ISSUE THREAD

**Issue by onetruffle** [yeyushengfan258/DeepinV20-dark-cursors#1]
Is it because of trademark issues? Deepin changed the theme's name from deepin to bloom. Is this going to help?

**Comment by yeyushengfan258** [comment]
Is Deepin

**Comment by onetruffle** [comment]
I made a pull request changing all instances of "deppin" to "deepin". Note that the original icon theme is now called bloom, not deepin.
